POST https://projetonode-5utl.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "nosso primeiro video",
    "duration": 180
}

###

GET https://projetonode-5utl.onrender.com/videos

###

PUT https://projetonode-5utl.onrender.com/videos/ef7752cf-b4f3-417e-a69e-f1ca4ac0a22e
Content-Type: application/json

{
    "title": "nosso primeiro vídeo",
    "description": "deu certo no Renderrrr tambémm =D",
    "duration": 180
}

###
DELETE https://projetonode-5utl.onrender.com/videos/c47744b9-9cbe-4839-a0ff-6b5936478c84

