POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "nosso primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/170c6dd9-90ca-446b-8f34-ea8ba0c308c4
Content-Type: application/json

{
    "title": "nosso primeiro vídeo",
    "description": "deu certo! =D",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/9a74648f-7c16-4a3d-83e0-fdb0ede50c27

